config/routes.rb
Rails.application.routes.draw do
  # routes for Hist
  mount Hist::Engine => '/hist'

  mount Ckeditor::Engine => '/ckeditor'

  #resources :homosaurus_v2

  #resources :homosaurus_v3

  # Generic file routes
  resources :generic_objects, path: :files, except: :index do
    collection do
      get 'batch_edit'
      post 'batch_add'
      post 'batch_replace'
      post 'batch_delete'
    end
    member do
      get 'stats'
      get 'citation'
      get 'make_public'
      get 'make_private'
      get 'make_redacted'
      get 'regenerate_thumbnail'
      get 'make_coll_image'
    end
  end

  scope module: 'admin', path: '/admin', as: 'admin' do
    get 'carousel_edit', to: 'admin#carousel_edit', as: :carousel_edit
    post 'carousel_update', to: 'admin#carousel_update', as: :carousel_update
  end

  # Collection routes
  resources :collections, path: :col, only: [:show, :index, :new, :edit, :create, :update, :destroy]
  #get 'col', :to => 'collections#public_index', :as => 'collections_public'
  #get 'col/:id', :to => 'collections#public_show', :as => 'collections_public_show'
  get 'col/facet/:id', :to => 'collections#facet', :as => 'collections_facet'
  # Added Institution Routes
  get 'ajax/cols/:id', :to => 'institutions#update_collections', :as => 'generic_files_update_collections'
  get 'ajax/cols', :to => 'institutions#update_collections', :as => 'generic_files_update_collections_no_id'

  get 'places', :to => 'catalog#map', :as => 'places'

  resources :institutions, path: :inst, only: [:show, :index, :new, :edit, :create, :update, :destroy]
  get 'inst/facet/:id', :to => 'institutions#facet', :as => 'institutions_facet'

  # Autocomplete Routes
  get '/autocomplete/creators', to: "autocomplete#creators", as: :creators_autocomplete
  get '/autocomplete/contributors', to: "autocomplete#contributors", as: :contributors_autocomplete
  get '/autocomplete/publishers', to: "autocomplete#publishers", as: :publishers_autocomplete
  get '/autocomplete/language', to: "autocomplete#languages", as: :languages_autocomplete
  get '/autocomplete/dates', to: "autocomplete#dates", as: :dates_autocomplete
  get '/autocomplete/homosaurus_subjects', to: "autocomplete#homosaurus_subject", as: :homosaurus_subject_autocomplete
  get '/autocomplete/homosaurus_v2_subjects', to: "autocomplete#homosaurus_v2_subject", as: :homosaurus_v2_subject_autocomplete
  get '/autocomplete/homosaurus_uri_subjects', to: "autocomplete#homosaurus_uri_subject", as: :homosaurus_uri_subject_autocomplete
  get '/autocomplete/geonames', to: "autocomplete#geonames_subject", as: :geonames_subject_autocomplete
  get '/autocomplete/lcsh_subjects', to: "autocomplete#lcsh_subject", as: :lcsh_subject_autocomplete
  get '/autocomplete/other_subjects', to: "autocomplete#other_subject", as: :other_subjects_autocomplete
  get '/autocomplete/exactMatch', to: "autocomplete#exact_match", as: :exact_match_autocomplete
  get '/autocomplete/closeMatch', to: "autocomplete#close_match", as: :close_match_autocomplete

  get '/autocomplete/exactMatch_lcsh', to: "autocomplete#lcsh_subject", as: :exact_match_lcsh_autocomplete
  get '/autocomplete/closeMatch_lcsh', to: "autocomplete#lcsh_subject", as: :close_match_lcsh_autocomplete
  get '/autocomplete/exactMatch_homosaurus', to: "autocomplete#homosaurus_subject", as: :exact_match_homosaurus_autocomplete
  get '/autocomplete/closeMatch_homosaurus', to: "autocomplete#homosaurus_subject", as: :close_match_homosaurus_autocomplete

  # Added Collection Routes
  get 'collections/members_public/:id' => 'collections#members_public', as: :collection_member_public
  get 'collections/members_private/:id' => 'collections#members_private', as: :collection_member_private
  get 'collections/collection_invisible/:id' => 'collections#collection_invisible', as: :collection_invisible
  get 'collections/collection_visible/:id' => 'collections#collection_visible', as: :collection_visible
  get 'collections/collection_thumbnail_set/:id/:item_id' => 'collections#collection_thumbnail_set', as: :collection_thumbnail_set

  #Static Paths
  resources :abouts, only: [:new, :edit, :create, :update, :show], :path => :about
  resources :learns, only: [:new, :edit, :create, :update, :show], :path => :learn
  resources :page_resources, only: [:new, :edit, :create, :update, :show], :path => :resources
  resources :posts, path: :news

  #get 'feedback' => 'abouts#feedback', as: :feedback
  #post 'feedback' => 'abouts#feedback'
  #get 'feedback_complete' => 'abouts#feedback_complete', as: :feedback_complete
  #get 'subscribe' => 'abouts#subscribe', as: :subscribe
  get 'contact' => 'contact#index', as: :contact
  post 'contact' => 'contact#index'
  #get 'feedback' => 'contact#feedback', as: :feedback
  #post 'feedback' => 'contact#feedback'
  get 'feedback_complete' => 'contact#feedback_complete', as: :feedback_complete

  #get 'about' => 'about#index', as: :about
  get 'about/project' => 'abouts#project', as: :about_project
  #get 'about/news' => 'abouts#news', as: :about_news
  get 'about/team' => 'abouts#team', as: :about_team
  get 'about/board' => 'abouts#board', as: :about_board
  get 'about/policies' => 'abouts#policies', as: :about_policies
  get 'about/contact' => 'abouts#contact', as: :about_contact

  get 'featured' => 'featured#index', as: :featured

  # FIXME: https://github.com/galetahub/ckeditor/issues/919
  get 'icons.png?t=08ffd39', to: redirect('/assets/ckeditor/skins/moono-lisa/icons.png?t=08ffd39')
  get 'icons_hidpi.png', to: redirect('/assets/ckeditor/skins/moono-lisa/icons_hidpi.png')
  get 'icons.png', to: redirect('/assets/ckeditor/skins/moono-lisa/icons.png')



  mount Blacklight::Engine => '/'
  #root to: "catalog#index"
  root to: 'homepage#index'
  devise_for :users
  mount Hydra::RoleManagement::Engine => '/'

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable
  end
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/files', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  


  # advanced routes for advanced search
  get 'search' => 'advanced#index', as: :advanced
  
  resources :downloads, only: 'show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # formats browse
  get 'genre', :to => 'catalog#genre_facet', :as => 'genre_facet'

  # subject browse
  get 'topic', :to => 'catalog#topic_facet', :as => 'topic_facet'

  authenticate :user, -> (user) { user.admin? } do
    mount Blazer::Engine => '/analytics'
  end

  require 'sidekiq/web'
  require 'tilt/erb' # Required for sidekiq-statistic to work
  require 'sidekiq-statistic'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

  resources 'oai',
            only: [:index]
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  include Blacklight::Catalog
  include DtaSearchHelper
  include DtaStaticBuilder

  copy_blacklight_config_from(CatalogController)

  before_action :get_latest_content

  before_action :update_search_builder, only: :index

  before_action :authenticate_user!, :except => [:show, :index, :facet]

  before_action :collection_base_blacklight_config, :only => [:show, :public_show, :facet]

  before_action :verify_admin, except: [:show, :index, :facet] #FIXME on change member

  #skip_load_and_authorize_resource :only => [:index, :facet], instance_name: :collection

  before_action :add_catalog_folder, only: [:index, :show, :facet]

  before_action  only: :show do
    if current_user.present? and current_user.contributor?
      blacklight_config.add_facet_field 'visibility_ssi', :label => 'Visibility', :limit => 4, :collapse => false
    end
  end

  # Blacklight uses #search_action_url to figure out the right URL for
  # the global search box
  def search_action_url options = {}
    search_catalog_url(options.except(:controller, :action))
  end
  helper_method :search_action_url

  def update_search_builder
    blacklight_config.search_builder_class = ::CollectionSearchBuilder
  end

  def collection_base_blacklight_config
    @skip_dta_limits_render = true
    blacklight_config.facet_fields['collection_name_ssim'].show = false
    blacklight_config.facet_fields['collection_name_ssim'].if = false

    blacklight_config.facet_fields['institution_name_ssim'].show = false
    blacklight_config.facet_fields['institution_name_ssim'].if = false

    #Needs to be fixed...
    blacklight_config.facet_fields['dta_dates_yearly_itim'].show = false
    blacklight_config.facet_fields['dta_dates_yearly_itim'].if = false
  end

  def range_limit
    redirect_to range_limit_catalog_path(params.except('controller', 'action')) and return
  end

  def index
    @nav_li_active = 'explore'
    (@response, @document_list) = search_results({:f => {'model_ssi' => 'Collection'}, :rows => 300, :sort => 'title_primary_ssort asc'})

=begin
    if params[:filter].present?
      new_doc_list = []
      @document_list.each do |doc|
        new_doc_list << doc if doc['title_primary_ssi'].upcase[0] == params[:filter]
      end
      @document_list = new_doc_list
    end
=end
    if params[:filter].present?
      new_document_list = []
      filter_list = params[:filter].split(',')
      @document_list.each do |doc|
        if filter_list.include?(doc['title_primary_ssi'].gsub(/^The /, "").upcase[0])
          new_document_list << doc
        end
      end
      @document_list = new_document_list
    end

    params[:view] = 'list'
    params[:sort] = 'title_info_primary_ssort asc'

    respond_to do |format|
      format.html
    end
  end

  def show
    @nav_li_active = 'explore'
    @show_response, @document = fetch(params[:id])

    # Get the ActiveRecord for this collection
    @collection = Coll.find_by(pid: params[:id])

    # add params[:f] for proper facet links
    params[:f] = set_collection_facet_params(@collection.title, @document)

    # get the response for the facets representing items in collection
    (@response, @document_list) = search_results({:f => params[:f]})
    # unless current_user.present? and current_user.contributor?
    #  ahoy.track_visit
    #  ahoy.track "Collection View", {title: @collection.title}, {pid: params[:id], model: "Collection"}
    # end

    respond_to do |format|
      format.html
    end
  end

  def destroy
    @collection = Coll.find_by(pid: params[:id])
    #@collection.generic_objects.each do |obj|
    #obj.soft_delete
    #end
    #@collection.visibility = 'deleted'
    if @collection.generic_objects.present?
      raise "Cannot delete a collection with items associated with it."
    else
      @collection.destroy!
      flash[:notice] = "Collection was deleted."
      redirect_to collections_path
    end
  end


  # set the correct facet params for facets from the collection
  def set_collection_facet_params(collection_title, document)
    facet_params = {blacklight_config.collection_field => [collection_title]}
    #facet_params[blacklight_config.institution_field] = document[blacklight_config.institution_field.to_sym]
    facet_params
  end

  def new
    @collection = Coll.new
  end

  def edit
    @collection = Coll.find_by(pid: params[:id])
  end

  def create
    @collection = Coll.new(collection_params)
    @collection.insts = Inst.where(pid: params['collection']['insts'])
    @collection.visibility = 'private'

    if @collection.save
      redirect_to collection_path(:id => @collection.pid), notice: "Collection was created!"
    else
      redirect_to new_collection_path
    end
  end


  def update
    @collection = Coll.find_by(pid: params[:id])

    @collection.update(collection_params)
    @collection.insts = Inst.where(pid: params['collection']['insts'])

    if @collection.save
      redirect_to collection_path(:id => @collection.pid), notice: "Collection was updated!"
    else
      redirect_to new_collection_path
    end
  end

  def members_public
    collection = Coll.find_by(pid: params[:id])
    collection.generic_objects.each do |obj|
      if obj.visibility == 'private'
        obj.visibility = 'public'
        obj.save!
      end
    end

    if collection.visibility == 'private'
      collection.visibility = 'public'
      collection.save!
    end

    flash[:notice] = "Visibility of all objects was made public!"
    redirect_to request.referrer
  end

  def members_private
    collection = Coll.find_by(pid: params[:id])
    collection.generic_objects.each do |obj|
      if obj.visibility == 'public'
        obj.visibility = 'private'
        obj.save!
      end
    end

    if collection.visibility == 'public'
      collection.visibility = 'private'
      collection.save!
    end

    flash[:notice] = "Visibility of all objects was made private!"
    redirect_to request.referrer
  end

  # FIXME
  def collection_thumbnail_set
    if @collection.thumbnail_ident != params[:item_id]
      @collection.thumbnail_ident = params[:item_id]
      @collection.save
      flash[:notice] = "Collection Image Was Set!"
    else
      flash[:notice] = "Could not set collection image (perhaps this was already set?)"
    end

    redirect_to request.referrer
  end


  def collection_params
    params.require(:collection).permit(:title, :description, :pid, :visibility)
  end

end

app/helpers/collections_helper.rb
module CollectionsHelper

  # link to view all items in a collection
  def link_to_all_col_items(col_title, institution_name=nil, link_class)
    facet_params = {blacklight_config.collection_field => [col_title]}
    facet_params[blacklight_config.institution_field] = institution_name if institution_name
#, :sort=>"dta_sortable_date_dtsi+asc%2C+title_primary_ssort+asc"
    link_to(t('blacklight.collections.browse.all'),
            search_catalog_path(:f => facet_params, :sort=>"dta_sortable_date_dtsi asc, title_primary_ssort asc"),
            :class => link_class)
    # search_catalog_url ?
    # catalog_index_path
  end

  # link to collections starting with a specific letter
  def link_to_cols_start_with(letter)
    link_to(letter,
            #collections_public_path(:q => 'title_info_primary_ssort:' + letter + '*'),
            collections_path(:filter=>letter),
            :class => 'col_a-z_link')
  end

  # whether the A-Z link menu should be displayed in collections#index
  def should_render_col_az?
    true
  end

  def make_links_clickable(str)
    match_strings = []
    local_str = str.clone

    while local_str.match(/https?:\/\/(?:www\.|(?!www))[^\s\.]+\.[^\s]{2,}|www\.[^\s]+\.[^\s]{2,}/) do
      match_strings << local_str.match(/https?:\/\/(?:www\.|(?!www))[^\s\.]+\.[^\s]{2,}|www\.[^\s]+\.[^\s]{2,}/)
      local_str.gsub!(match_strings[-1].to_s, '')
    end

    match_strings.each do |match_string|
      str.gsub!(match_string.to_s, "<a href='#{match_string.to_s}' title='Click here to visit #{match_string.to_s} (new window)' target='_blank'>#{match_string.to_s}</a>")
    end
    str
  end


  #COPIED FROM HYDRA COLLECTIONS COLLECTIONS HELPER
  # Displays the Collections create collection button.  Put this in your search result page template.  We recommend putting it in catalog/_sort_and_per_page.html.erb
  def button_for_create_collection(label = 'Create Collection')
    render partial:'/collections/button_create_collection', locals:{label:label}
  end

  # Displays the Collections update collection button.  Put this in your search result page template.  We recommend putting it in catalog/_sort_and_per_page.html.erb
  def button_for_update_collection(label = 'Update Collection', collection_id = 'collection_replace_id' )
    render partial:'/collections/button_for_update_collection', locals:{label:label, collection_id:collection_id}
  end

  # Displays the Collections delete collection button.  Put this in your search result page for each collection found.
  def button_for_delete_collection(collection, label = 'Delete Collection', confirm = 'Are you sure?')
    render partial:'/collections/button_for_delete_collection', locals:{collection:collection,label:label, confirm:confirm}
  end

  def button_for_remove_from_collection(document, label = 'Remove From Collection')
    render partial:'/collections/button_remove_from_collection', locals:{label:label, document:document}
  end

  def button_for_remove_selected_from_collection(collection, label = 'Remove From Collection')
    render partial:'/collections/button_for_remove_selected_from_collection', locals:{collection:collection, label:label}
  end


  # add hidden fields to a form for removing a single document from a collection
  def single_item_action_remove_form_fields(form, document)
    single_item_action_form_fields(form, document, "remove")
  end

  # add hidden fields to a form for adding a single document to a collection
  def single_item_action_add_form_fields(form, document)
    single_item_action_form_fields(form, document, "add")
  end

  # add hidden fields to a form for performing an action on a single document on a collection
  def single_item_action_form_fields(form, document, action)
    render partial:'/collections/single_item_action_fields', locals:{form:form, document:document, action: action}
  end

  def hidden_collection_members
    _erbout = ''
    if params[:batch_document_ids].present?
      params[:batch_document_ids].each do |batch_item|
        _erbout.concat hidden_field_tag("batch_document_ids[]", batch_item)
      end
    end
    _erbout.html_safe
  end

end

app/views/collections/_action_menu.html.erb
<div class="btn-group">
  <button class="btn btn-sm dropdown-toggle" data-toggle="dropdown">Select an action <span class="caret"></span></button>
  <ul class="dropdown-menu dropdown-menu-right">

    <li>
      <%= link_to raw('<i class="glyphicon glyphicon-picture"></i> Set as Thumbnail'), collection_thumbnail_set_path(:id=>@collection_id, :item_id=>id),
                  class: 'itemicon', title: 'Set as Thumbnail' %>
    </li>
    <li>
      <%= link_to raw('<i class="glyphicon glyphicon-link over"></i> Single-Use Link to File'), '#',
                  class: "copypaste itemicon itemcode", title: "Single-Use Link to File", id: "copy_link_#{id}" %>
    </li>
    <li>
      <%= link_to raw('<i class="glyphicon glyphicon-pencil"></i> Edit File'), sufia.edit_generic_file_path(id),
                  class: 'itemicon itemedit', title: 'Edit File' %>
    </li>
    <li>
      <%= link_to raw('<i class="glyphicon glyphicon-download-alt"></i> Download File'), sufia.download_path(id),
                  class: 'itemicon itemdownload', title: 'Download File', target: '_new' %>
    </li>
    <li>
      <%= display_trophy_link(@user, id) do |text| %>
          <i class='glyphicon glyphicon-star'></i> <%= text %>
      <% end %>
    </li>
    <li>
      <%=  button_for_remove_from_collection(gf, 'Remove from Collection (FIXME)') %>
    </li>
  </ul>
</div>

app/views/collections/_show_actions.html.erb
<h2 class="sr-only">Actions</h2>
<div class="actions-controls-collections">
  <% if can? :edit, @collection %>
      <% if current_user.admin? %>
          <span class="label label-default"><%= link_to t("sufia.collection.show.edit.label"), collections.edit_collection_path, title: t("sufia.collection.show.edit.label") %></span> &nbsp;&nbsp;
          <span class="label label-default"><%= link_to 'Make All Visible', collection_member_visibility_path(@collection.id), title: 'Make All Visible' %></span> &nbsp;&nbsp;
          <span class="label label-default"><%= link_to 'Hide Collection + Items', collection_invisible_path(@collection.id), title: 'Hide Collection' %></span> &nbsp;&nbsp;
          <span class="label label-default"><%= link_to 'Make Collection Only Visible', collection_visible_path(@collection.id), title: 'Make Collection Only Visible' %></span> &nbsp;&nbsp;
      <% end %>

      <span class="label label-default"><%= link_to t("sufia.collection.show.add_files.label"),  sufia.dashboard_files_path( add_files_to_collection: @collection.id ), title: t("sufia.collection.show.add_files.label") %></span>
      <% if Sufia.config.upload_to_collection %>
          <div class="actions-controls-collections-line2">
            <span class="label label-default"><%= link_to t("sufia.collection.show.upload_files.label"),  sufia.new_generic_file_path( collection: @collection.id ), title: t("sufia.collection.show.upload_files.desc") %></span>
          </div>
      <%end %>
  <%end %>
</div>

app/views/collections/_show_collection_list.html.erb
<table class="table table-zebra-striped inst_collection_table">
  <caption class="sr-only">List of collection</caption>
  <tbody>
    <%= render partial: 'show_collection_list_row', collection: documents, as: :document %>
  </tbody>
</table>

app/views/collections/index.html.erb
<% @page_title = t('blacklight.collections.index.page_title', :application_name => application_name) + " - " +  application_name %>
<% content_for(:head) { render_opensearch_response_metadata } %>

<div id="collections-index">
  <div id="sidebar" class="col-md-3 col-sm-3">
    <div class="side_nav_custom">
      <h4>Browse By</h4>

      <ul class="content">
        <li><%= link_to 'By Map', '/places' %></li>
        <li><%= link_to 'By Institution', institutions_path %></li>
        <li class="active"><%= link_to 'By Collection', collections_path %></li>
        <li><%= link_to 'By Topic', topic_facet_path %></li>
        <li><%= link_to 'By Genre', genre_facet_path %></li>
        <li><%= link_to 'By Latest', '/catalog?utf8=%E2%9C%93&sort=date_uploaded_dtsi+desc&search_field=all_fields&q=' %></li>
      </ul>
    </div>
  </div>

  <a name="top"></a>
  <div id="content" class="col-md-9 col-sm-9 collections-list">
    <div class="inst_collection_table">
      <h2>Collections</h2>
    </div>

    <div id="browse_by_title">
      <h4>Browse By Title:</h4>
      <ul>
        <li <% if params[:filter].nil? %>class="active"<% end %>><%= link_to 'ALL', collections_path %></li>
        <li <% if params[:filter] == 'A,B,C,D' %>class="active"<% end %>><%= link_to "A — D", collections_path(filter: 'A,B,C,D') %></li>
        <li <% if params[:filter] == 'E,F,G,H,I,J' %>class="active"<% end %>><%= link_to "E — J", collections_path(filter: 'E,F,G,H,I,J') %></li>
        <li <% if params[:filter] == 'K,L,M,N,O' %>class="active"<% end %>><%= link_to "K — O", collections_path(filter: 'K,L,M,N,O') %></li>
        <li <% if params[:filter] == 'P,Q,R,S,T' %>class="active"<% end %>><%= link_to "P — T", collections_path(filter: 'P,Q,R,S,T') %></li>
        <li <% if params[:filter] == 'U,V,X,Y,Z' %>class="active"<% end %>><%= link_to "U — Z", collections_path(filter: 'U,V,X,Y,Z') %></li>

      </ul>
      <div style="clear:both"></div>
    </div>

    <h2 class="sr-only"><%= t('blacklight.search.search_results') %></h2>

    <%= render 'collections/show_collection_list', :documents => @document_list %>

    <%= render 'catalog/results_pagination' %>

  </div>

</div>

<%= render partial: "partials/back_to_top" %>

app/views/collections/show.html.erb
<% @page_title = "#{@collection.title} - #{application_name}" %>
<div id="collections-show">
  <% content_for(:head) { render_link_rel_alternates } %>

  <div id="doc_<%= @document.id.to_s.parameterize %>">

    <div id="breadcrumbs-title">
      <ul class="breadcrumb">
        <li class="breadcrumb-back"><%= link_to 'Collections', collections_path %></li>
        <li class="breadcrumb-title"><%= @collection.title %></li>
      </ul>
    </div>

    <div class="document">

      <div class="row">

        <div class="col-md-9 col-sm-8 maximize_custom">
          <div id="inst_image">
            <%= render_thumbnail_tag @document, { class: "collection_img_show" }, { suppress_link: true } %>
          </div>

          <div id="institution_search_tools" >
            <%= render :partial => 'search_form_collection', :locals => {:document => @document} %>
          </div>


          <div id="inst_info">

            <div id="institution_desc">

              <% if @document[:description_tesim] %>
                <% @document[:description_tesim].each do |abstract| %>
                  <%=
                    make_links_clickable(abstract).html_safe
                  %>
                <% end %>
              <% end %>

              <p>    <br />
                <% if @collection.insts.size == 1 %>
                  This collection has been provided by:
                <% else %>
                  The following institutions have contributed to this collection:
                <% end %>
              <ul>
                <% @collection.insts.pluck(:name, :pid).sort.each do |inst_name, inst_pid| %>
                  <li class="external_site_link"><%= link_to inst_name, institution_path(inst_pid) %></li>
                <% end %>
              </ul>
              </p>

            </div>
          </div>
          <div id="institution_view_all" class="pull-left">
            <%= link_to_all_col_items(@collection.title, nil, 'btn view-all-inst') %>
          </div>
          <div style="clear: both;"></div>

          <% if current_user.present? and current_user.admin? %>
            <div style="clear:left; float: left;">
              <%= render partial: 'collections/partials/collection_menu', locals: { pid: @collection.pid } %>
            </div>
          <% end %>
        </div>
        <div id="sidebar" class="col-md-3 col-sm-4 pull-right hidetest">
          <%= render partial: '/catalog/facets', locals: { skip_title: false } %>
        </div>

        <div class="col-md-9 col-sm-8 maximize_custom">

          <% # map for collections#show view %>
          <% unless @response.aggregations[map_facet_field].items.empty? %>
            <div id="blacklight-collection-map-container">
              <h4>Map View:</h4>
              <%= render :partial => 'catalog/index_mapview',
                         :locals => {:geojson_features => serialize_geojson(map_facet_values,
                                                                            'index')} %>
            </div>
            </div>
          <% end %>

          </div>




    </div>

  </div>


</div>


</div>

app/views/collections/show_orig.html.erb
<% @page_title = "#{@collection.title} - #{application_name}" %>
<div style="max-width:1400px; margin: 0 auto">


<div class="document">

  <div itemscope itemtype="http://schema.org/CollectionPage" class="row">

    <div class="col-sm-9">
      <div id="collection_img">
        <h2 class="collection-title" style="text-align: center; margin-top: 18px;"><%= @collection.title %></h2>
        <%= render_thumbnail_tag @document, { class: "collection_img_show" }, { suppress_link: true } %>
        <% if current_user.present? and current_user.admin? %>
            <br /><br />
            <%= render partial: 'collections/partials/collection_menu', locals: { pid: @collection.pid } %>
        <% end %>
      </div>

      <div id="collection_search_tools" class="well well-sm" style="margin-top:53px;">
        <%= render :partial => 'search_form_collection', :locals => {:document => @document} %>
        <span class="collection_search_separator">or</span>
        <div id="collection_view_all">

              <%= link_to_all_col_items(@collection.title,
                                        nil,
                                        'btn btn-info view-all-col') %>

        </div>
      </div>

      <div id="collection_desc">
        <% if @document[:description_tesim] %>
            <% @document[:description_tesim].each do |abstract| %>
                <%=
                  make_links_clickable(abstract).html_safe
                %>
            <% end %>
        <% end %>

        <p>    <br />
          <% if @collection.insts.size == 1 %>
              This collection has been provided by:
          <% else %>
              The following institutions have contributed to this collection:
        <% end %>
            <ul>
              <% @collection.insts.pluck(:name, :pid).sort.each do |inst_name, inst_pid| %>
                  <li><%= link_to inst_name, institution_path(inst_pid) %></li>
              <% end %>
            </ul>
        </p>
      </div>

      <% # map for collections#show view %>
      <% unless @response.aggregations[map_facet_field].items.empty? %>
          <div id="blacklight-collection-map-container">
            <h4><%= t('blacklight.collections.map.title') %></h4>
            <%= render :partial => 'catalog/index_mapview',
                       :locals => {:geojson_features => serialize_geojson(map_facet_values,
                                                                          'index')} %>
          </div>
          </div>
      <% end %>

      </div>

  <div id="sidebar" class="col-sm-3" style="margin-top: 32px;">
    <%= render partial: '/catalog/facets', locals: {skip_title: true} %>
  </div>


</div>
</div>
</div>