config/routes.rb
Rails.application.routes.draw do
  # routes for Hist
  mount Hist::Engine => '/hist'

  mount Ckeditor::Engine => '/ckeditor'

  #resources :homosaurus_v2

  #resources :homosaurus_v3

  # Generic file routes
  resources :generic_objects, path: :files, except: :index do
    collection do
      get 'batch_edit'
      post 'batch_add'
      post 'batch_replace'
      post 'batch_delete'
    end
    member do
      get 'stats'
      get 'citation'
      get 'make_public'
      get 'make_private'
      get 'make_redacted'
      get 'regenerate_thumbnail'
      get 'make_coll_image'
    end
  end

  scope module: 'admin', path: '/admin', as: 'admin' do
    get 'carousel_edit', to: 'admin#carousel_edit', as: :carousel_edit
    post 'carousel_update', to: 'admin#carousel_update', as: :carousel_update
  end

  # Collection routes
  resources :collections, path: :col, only: [:show, :index, :new, :edit, :create, :update, :destroy]
  #get 'col', :to => 'collections#public_index', :as => 'collections_public'
  #get 'col/:id', :to => 'collections#public_show', :as => 'collections_public_show'
  get 'col/facet/:id', :to => 'collections#facet', :as => 'collections_facet'
  # Added Institution Routes
  get 'ajax/cols/:id', :to => 'institutions#update_collections', :as => 'generic_files_update_collections'
  get 'ajax/cols', :to => 'institutions#update_collections', :as => 'generic_files_update_collections_no_id'

  get 'places', :to => 'catalog#map', :as => 'places'

  resources :institutions, path: :inst, only: [:show, :index, :new, :edit, :create, :update, :destroy]
  get 'inst/facet/:id', :to => 'institutions#facet', :as => 'institutions_facet'

  # Autocomplete Routes
  get '/autocomplete/creators', to: "autocomplete#creators", as: :creators_autocomplete
  get '/autocomplete/contributors', to: "autocomplete#contributors", as: :contributors_autocomplete
  get '/autocomplete/publishers', to: "autocomplete#publishers", as: :publishers_autocomplete
  get '/autocomplete/language', to: "autocomplete#languages", as: :languages_autocomplete
  get '/autocomplete/dates', to: "autocomplete#dates", as: :dates_autocomplete
  get '/autocomplete/homosaurus_subjects', to: "autocomplete#homosaurus_subject", as: :homosaurus_subject_autocomplete
  get '/autocomplete/homosaurus_v2_subjects', to: "autocomplete#homosaurus_v2_subject", as: :homosaurus_v2_subject_autocomplete
  get '/autocomplete/homosaurus_uri_subjects', to: "autocomplete#homosaurus_uri_subject", as: :homosaurus_uri_subject_autocomplete
  get '/autocomplete/geonames', to: "autocomplete#geonames_subject", as: :geonames_subject_autocomplete
  get '/autocomplete/lcsh_subjects', to: "autocomplete#lcsh_subject", as: :lcsh_subject_autocomplete
  get '/autocomplete/other_subjects', to: "autocomplete#other_subject", as: :other_subjects_autocomplete
  get '/autocomplete/exactMatch', to: "autocomplete#exact_match", as: :exact_match_autocomplete
  get '/autocomplete/closeMatch', to: "autocomplete#close_match", as: :close_match_autocomplete

  get '/autocomplete/exactMatch_lcsh', to: "autocomplete#lcsh_subject", as: :exact_match_lcsh_autocomplete
  get '/autocomplete/closeMatch_lcsh', to: "autocomplete#lcsh_subject", as: :close_match_lcsh_autocomplete
  get '/autocomplete/exactMatch_homosaurus', to: "autocomplete#homosaurus_subject", as: :exact_match_homosaurus_autocomplete
  get '/autocomplete/closeMatch_homosaurus', to: "autocomplete#homosaurus_subject", as: :close_match_homosaurus_autocomplete

  # Added Collection Routes
  get 'collections/members_public/:id' => 'collections#members_public', as: :collection_member_public
  get 'collections/members_private/:id' => 'collections#members_private', as: :collection_member_private
  get 'collections/collection_invisible/:id' => 'collections#collection_invisible', as: :collection_invisible
  get 'collections/collection_visible/:id' => 'collections#collection_visible', as: :collection_visible
  get 'collections/collection_thumbnail_set/:id/:item_id' => 'collections#collection_thumbnail_set', as: :collection_thumbnail_set

  #Static Paths
  resources :abouts, only: [:new, :edit, :create, :update, :show], :path => :about
  resources :learns, only: [:new, :edit, :create, :update, :show], :path => :learn
  resources :page_resources, only: [:new, :edit, :create, :update, :show], :path => :resources
  resources :posts, path: :news

  #get 'feedback' => 'abouts#feedback', as: :feedback
  #post 'feedback' => 'abouts#feedback'
  #get 'feedback_complete' => 'abouts#feedback_complete', as: :feedback_complete
  #get 'subscribe' => 'abouts#subscribe', as: :subscribe
  get 'contact' => 'contact#index', as: :contact
  post 'contact' => 'contact#index'
  #get 'feedback' => 'contact#feedback', as: :feedback
  #post 'feedback' => 'contact#feedback'
  get 'feedback_complete' => 'contact#feedback_complete', as: :feedback_complete

  #get 'about' => 'about#index', as: :about
  get 'about/project' => 'abouts#project', as: :about_project
  #get 'about/news' => 'abouts#news', as: :about_news
  get 'about/team' => 'abouts#team', as: :about_team
  get 'about/board' => 'abouts#board', as: :about_board
  get 'about/policies' => 'abouts#policies', as: :about_policies
  get 'about/contact' => 'abouts#contact', as: :about_contact

  get 'featured' => 'featured#index', as: :featured

  # FIXME: https://github.com/galetahub/ckeditor/issues/919
  get 'icons.png?t=08ffd39', to: redirect('/assets/ckeditor/skins/moono-lisa/icons.png?t=08ffd39')
  get 'icons_hidpi.png', to: redirect('/assets/ckeditor/skins/moono-lisa/icons_hidpi.png')
  get 'icons.png', to: redirect('/assets/ckeditor/skins/moono-lisa/icons.png')



  mount Blacklight::Engine => '/'
  #root to: "catalog#index"
  root to: 'homepage#index'
  devise_for :users
  mount Hydra::RoleManagement::Engine => '/'

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable
  end
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/files', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  


  # advanced routes for advanced search
  get 'search' => 'advanced#index', as: :advanced
  
  resources :downloads, only: 'show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # formats browse
  get 'genre', :to => 'catalog#genre_facet', :as => 'genre_facet'

  # subject browse
  get 'topic', :to => 'catalog#topic_facet', :as => 'topic_facet'

  authenticate :user, -> (user) { user.admin? } do
    mount Blazer::Engine => '/analytics'
  end

  require 'sidekiq/web'
  require 'tilt/erb' # Required for sidekiq-statistic to work
  require 'sidekiq-statistic'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

  resources 'oai',
            only: [:index]
end

app/controllers/catalog_controller.rb
# frozen_string_literal: true
class CatalogController < ApplicationController
  include BlacklightRangeLimit::ControllerOverride
  include BlacklightMaps::ControllerOverride
  include DtaSearchHelper

  include Blacklight::Catalog
  include DtaStaticBuilder

  #layout "sufia-one-column"
  #layout "local_blacklight"

  before_action :get_latest_content
  #before_action :enforce_show_permissions, only: :show
  #skip_before_action :default_html_head

  #CatalogController.search_params_logic += [:add_access_controls_to_solr_params, :add_advanced_parse_q_to_solr, :exclude_unwanted_models]

  before_action  only: [:index, :facet] do
    if current_user.present? and current_user.contributor?
      blacklight_config.add_facet_field 'publisher_ssim', :label => 'Publisher', :limit => 6, :sort => 'index', :collapse => true, :show => true
      blacklight_config.add_facet_field 'visibility_ssi', :label => 'Visibility', :limit => 4, :collapse => false
      blacklight_config.add_facet_field 'dta_homosaurus_v1_subject_ssim', :label => 'Homosaurus V1', :limit => 6, :sort => 'index', :collapse => false

      uploaded_field = 'date_uploaded_dtsi'
      modified_field = 'date_modified_dtsi'
      blacklight_config.add_sort_field "#{uploaded_field} desc", label: "date uploaded \u25BC"
      blacklight_config.add_sort_field "#{uploaded_field} asc", label: "date uploaded \u25B2"
      blacklight_config.add_sort_field "#{modified_field} desc", label: "date modified \u25BC"
      blacklight_config.add_sort_field "#{modified_field} asc", label: "date modified \u25B2"

      blacklight_config.add_sort_field 'collection_name_ssort asc, dta_sortable_date_dtsi asc', :label => "collection \u25B2"
      blacklight_config.add_sort_field 'collection_name_ssort desc, dta_sortable_date_dtsi asc', :label => "collection \u25BC"

      blacklight_config.add_sort_field 'visibility_ssi asc, dta_sortable_date_dtsi asc', :label => "visibility \u25B2"
      blacklight_config.add_sort_field 'visibility_ssi desc, dta_sortable_date_dtsi asc', :label => "visibility \u25BC"

      blacklight_config.add_index_field 'visibility_ssi', :label => 'Visbility'
    else
      blacklight_config.add_facet_field 'publisher_ssim', :label => 'Publisher', :limit => 6, :sort => 'index', :collapse => true, :show => false
    end
  end

  def has_search_parameters?
    params[:dtalimits].present? || super
  end

  configure_blacklight do |config|
    #config.add_facet_field 'publisher_ssim', :label => 'Publisher', :limit => 6, :sort => 'index', :collapse => true, :show => true

    # collection name field
    config.collection_field = 'collection_name_ssim'
    # institution name field
    config.institution_field = 'institution_name_ssim'
    # solr field for flagged/inappropriate content
    config.flagged_field = 'flagged_ssi'

    #config.view.gallery.default = true # List is now the default
    config.view.gallery.partials = [:index_header, :index]
    config.view.masonry.partials = [:index]
    config.view.slideshow.partials = [:index]

    config.show.tile_source_field = :content_metadata_image_iiif_info_ssm
    config.show.partials.insert(1, :openseadragon)

    # Show gallery view
    config.view.gallery.partials = [:index_header, :index]
    config.view.slideshow.partials = [:index]

    # blacklight-maps stuff
    config.view.maps.geojson_field = 'subject_geojson_facet_ssim'
    config.view.maps.coordinates_field = 'subject_coordinates_geospatial'
    config.view.maps.placename_field = 'subject_geographic_ssim'
    config.view.maps.maxzoom = 13
    config.view.maps.show_initial_zoom = 9
    config.view.maps.facet_mode = 'geojson'

    #set default per-page
    config.default_per_page = 15
    config.per_page = [15,25,50,100,200]

    #config.max_per_page = 300
    config.max_per_page = 2000

    ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params
    config.default_solr_params = {
        qt: "search",
        rows: 20
    }

    config.search_builder_class = ::DefaultSearchBuilder

    config.index.title_field = 'title_tesim'
    config.index.display_type_field = 'blacklight_display_ssi'
    config.index.thumbnail_method = :dta_thumbnail_tag

    config.add_facet_field 'dtalimits', label: "Limit", :show => false, query: {
        :ex_fa => { label: 'Exclude Finding Aids', fq: '-genre_ssim:"Finding Aids"' }
    }
    config.add_facet_field 'creator_ssim', label: "Creator", limit: 6, collapse:false
    config.add_facet_field 'dta_all_subject_ssim', :label => 'Topic', :limit => 6, :sort => 'count', :collapse => false
    config.add_facet_field 'dta_other_subject_ssim', :label => 'Subject', :limit => 6, :sort => 'count', :collapse => false
    config.add_facet_field 'dta_dates_yearly_itim', :label => 'Date', :range => { num_segments: 6}, :collapse => false
    config.add_facet_field 'genre_ssim', :label => 'Genre', :limit => 6, :sort => 'count', :collapse => true
    config.add_facet_field 'subject_geographic_ssim', :label => 'Location', :limit => 6, :sort => 'count', :collapse => true
    config.add_facet_field 'language_label_ssim', :label => 'Language', :limit => 6, :sort => 'count', :collapse => true
    config.add_facet_field 'collection_name_ssim', :label => 'Collection', :limit => 8, :sort => 'count', :collapse => true
    config.add_facet_field 'institution_name_ssim', :label => 'Institution', :limit => 8, :sort => 'count', :collapse => true
    config.add_facet_field 'subject_geojson_facet_ssim', :limit => -2, :label => 'Coordinates', :show => false

    config.add_facet_fields_to_solr_request!

    config.add_index_field 'collection_name_ssim', :label => 'Collection'
    config.add_index_field 'institution_name_ssim', :label => 'Institution'
    config.add_index_field "creator_ssim", label: "Creator", itemprop: 'creator'
    config.add_index_field 'date_created_display_ssim', :label => 'Date'
    config.add_index_field 'date_issued_display_ssim', :label => 'Date'

    config.add_search_field('all_fields') do |field|
      field.label = 'All Text'
      field.include_in_advanced_search = false
      field.solr_parameters = { :'spellcheck.dictionary' => 'default' }
    end

    config.add_search_field('title') do |field|
      #field.solr_parameters = { :'spellcheck.dictionary' => 'title' }

      #field.solr_local_parameters = {
          #qf: '$title_qf',
          #pf: '$title_pf'
      #}
      field.solr_parameters = {
          'spellcheck.dictionary': 'title',
          qf: '${title_qf}',
          pf: '${title_pf}'
      }
    end

    config.add_search_field('description') do |field|
      field.solr_parameters = {
          'spellcheck.dictionary': 'description',
          qf: '${description_qf}',
          pf: '${description_pf}'
      }
    end

    config.add_search_field('creator') do |field|
      field.solr_parameters = {
          'spellcheck.dictionary': 'creator',
          qf: '${creator_qf}',
          pf: '${creator_pf}'
      }
    end

    config.add_search_field('publisher') do |field|
      field.solr_parameters = {
          'spellcheck.dictionary': 'publisher',
          qf: '${publisher_qf}',
          pf: '${publisher_pf}'
      }
    end

    config.add_search_field('othersubject') do |field|
      #field.label = 'People / Organizations'
      #field.label = 'People'
      field.label = 'Subject'

      field.solr_parameters = {
          'spellcheck.dictionary': 'othersubject',
          qf: '${othersubject_qf}',
          pf: '${othersubject_pf}'
      }
    end

    config.add_search_field('identifier') do |field|
      field.label = 'Identifier'

      field.solr_parameters = {
          'spellcheck.dictionary': 'identifier',
          qf: '${identifier_qf}',
          pf: '${identifier_pf}'
      }
    end

    # "sort results by" select (pulldown)
    # label in pulldown is followed by the name of the SOLR field to sort by and
    # whether the sort is ascending or descending (it must be asc or desc
    # except in the relevancy case).
    config.add_sort_field 'score desc, title_primary_ssort asc', :label => 'relevance'
    config.add_sort_field 'title_primary_ssort asc, dta_sortable_date_dtsi asc', :label => "title \u25B2"
    config.add_sort_field 'title_primary_ssort desc, dta_sortable_date_dtsi asc', :label => "title \u25BC"
    config.add_sort_field 'dta_sortable_date_dtsi asc, title_primary_ssort asc', :label => "date \u25B2"
    config.add_sort_field 'dta_sortable_date_dtsi desc, title_primary_ssort asc', :label => "date \u25BC"

    # If there are more than this many search results, no spelling ("did you
    # mean") suggestion is offered.
    config.spell_max = 10

    # Configuration for autocomplete suggestor
    config.autocomplete_enabled = true
    config.autocomplete_path = 'suggest'
  end

  # displays values and pagination links for Format field
  def genre_facet
    @nav_li_active = 'explore'
    @facet_no_more_link = true

    @facet = blacklight_config.facet_fields['genre_ssim']
    @response = get_facet_field_response(@facet.key, params)
    @display_facet = @response.aggregations[@facet.key]

    @pagination = facet_paginator(@facet, @display_facet)

    render :full_browse_facet
  end

  def topic_facet
    @nav_li_active = 'explore'
    @facet_no_more_link = true

    @facet = blacklight_config.facet_fields['dta_all_subject_ssim']
    @response = get_facet_field_response(@facet.key, params)
    @display_facet = @response.aggregations[@facet.key]

    @pagination = facet_paginator(@facet, @display_facet)

    render :full_browse_facet
  end
end

app/helpers/catalog_helper.rb
module CatalogHelper
  include Blacklight::CatalogHelperBehavior

# render the date in the catalog#index list view
  def index_date_value options={}
    document = options[:document]
    if document[:date_created_tesim]
      document[:date_created_tesim].first
    elsif document[:date_issued_tesim]
      document[:date_issued_tesim].first
    else
      nil
    end
  end

  def institution_icon_path
    'shared/institution_icon.png'
  end

# determine the 'truncate' length based on catalog#index view type
  def index_title_length
    case params[:view]
      when 'list'
        170
      when 'masonry'
        89
      else
        130
    end
  end


end

app/views/catalog/_show_partials/_dta_admin_facet.html.erb
<div class="panel panel-default facet_limit blacklight-admin_functions ">
  <div class=" collapse-toggle panel-heading" data-toggle="collapse" data-target="#admin_functions">
    <h3 class="panel-title facet-field-heading">
      <a data-turbolinks="false" data-no-turbolink="true" href="#">Admin Functions</a>
    </h3>
  </div>
  <div id="facet-admin_functions" class="panel-collapse facet-content in">
    <div class="panel-body">
      <ul class="facet-values list-unstyled">
        <li>
          <span class="facet-label">
            <%= link_to 'Batch Edit', batch_edit_generic_objects_path(request.parameters), { :class=>"facet_select" }  %>
          </span>
          <span class="facet-count" style="width: 6px;"><%= @response.total_count %></span>

      </ul>


    </div>
  </div>
</div>

app/views/catalog/_show_partials/_dta_limits_facet.html.erb
<% # main container for facets/limits menu -%>
<script type="text/javascript">
  //According to the docs, one could set both "focus" and "click" events.
  //However, it doesn't seem to work right so doing this manually.
  //Docs: http://getbootstrap.com/javascript/#popovers
  $(document).ready(function(){
    $('#dtalimits_fa_help').click(function(){
      $('#dtalimits_fa_help').popover('toggle');
      return false;
    }).focusout(function() {
      $('#dtalimits_fa_help').popover('hide');
    });
  });
</script>

<style type="text/css">
  .dtalimits_checkboxes input { float: left; margin-top:6px;}
  .dtalimits_checkboxes label { display: block; margin-left: 3px; padding-top:2px;}

  #dtalimits_fa_help {
    float: left;
    margin-left: 3px;
  }

  #dtalimits_fa_help i.help-icon {
    font-size: 1.1em;
    margin-top:-7px;

  }

  #facet-dtalimits_fa .popover {
    position: absolute;
    top: 0;
    left: 0;
    z-index: 1060;
    display: none;
    max-width: 276px;
    padding: 1px;
    font-style: normal;
    font-weight: normal;
    letter-spacing: normal;
    line-break: auto;
    line-height: 1.42857143;
    text-align: left;
    text-align: start;
    text-decoration: none;
    text-shadow: none;
    text-transform: none;
    white-space: normal;
    word-break: normal;
    word-spacing: normal;
    word-wrap: normal;
    font-size: 14px;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ccc;
    border: 1px solid rgba(0, 0, 0, 0.2);
    border-radius: 6px;
    -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
    box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
    color:#333333;
  }

  #facet-dtalimits_fa .popover-title { display: none; }


  .dtalimits_checkboxes {
    clear:both;
  }



  .dtalimits_selected {
    color: rgb(60, 118, 61);
    background-color: rgb(223, 240, 216);
    border-bottom-color: rgb(214, 233, 198);
    border-left-color: rgb(214, 233, 198);
    border-right-color: rgb(214, 233, 198);
    border-top-color: rgb(214, 233, 198);
    padding-top: 7px;
    margin-bottom: -8px;

  }

  .panel-dta_limits {
    padding-top:7px;
    padding-bottom: 7px;
    padding-right:0px;
    margin-right:0px;
    padding-left:12px;
  }
</style>


  <div class="panel panel-default facet_limit blacklight-dtalimits_fa <%if facet_in_params?(:dtalimits, "ex_fa")%>dtalimits_selected<%end%>">
    <div id="facet-dtalimits_fa" class="panel-collapse facet-content in">
      <div class="panel-body panel-dta_limits">
        <div class="dtalimits_checkboxes">
          <% dtalimits_item = 'ex_fa'
             dtalimits_facet_field = 'dtalimits'
          %>
          <% if facet_in_params?(:dtalimits, "ex_fa") %>
              <% dtalimits_path = search_action_path(remove_facet_params(dtalimits_facet_field, dtalimits_item, params)) %>
              <%= check_box_tag 'exclude_finding_aids', 'exclude_finding_aids', true, :id => 'exclude_finding_aids_checkbox', :onclick=>"window.location.assign('#{dtalimits_path}');this.disabled=true;" %>
          <% else %>
              <% dtalimits_path = path_for_facet(dtalimits_facet_field, dtalimits_item) %>
              <%= check_box_tag 'exclude_finding_aids', 'exclude_finding_aids', false, :id => 'exclude_finding_aids_checkbox', :onclick=>"window.location.assign('#{dtalimits_path}');this.disabled=true;" %>
          <% end %>
          <%= label_tag(:online_only, "Exclude Finding Aids", :id => "exclude_finding_aids_checkbox_label", :style=>"font-weight:normal; float:left;") %>
          <%= link_to '#', id: "dtalimits_fa_help", rel: 'popover'.freeze,
                      'data-content' => 'Check this box to limit your search results to digital or digitized historical materials. Finding aids are documents that describe collections held in archives and they may not be relevant for all researchers.', 'data-original-title' => 'Exclude Finding Aids',
                      'aria-label' => 'Exclude Finding Aids', 'data-trigger' => 'manual', 'data-placement' => 'bottom', style: "padding-top: 3px;" do
            content_tag 'i', nil, "aria-hidden" => true, class: "help-icon glyphicon glyphicon-question-sign"
          end %>

        </div>

      </div>
    </div>
  </div>

app/views/catalog/_show_partials/_show_flagged_notice.html.erb
<div class="modal fade" id="flagged_warning" tabindex="-1" role="dialog" aria-labelledby="flaggedWarning">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">EXPLICIT CONTENT WARNING</h3>
      </div>
      <div class="modal-body">
        <% if @generic_file.flagged_category.empty? %>
          <p><strong>This item contains content that could be offensive to some viewers or inappropriate for minors.</strong></p>
        <% else %>
          <p><strong>This item contains content that could be offensive to some viewers or inappropriate for minors because it relates to:
          <ul>
            <% @generic_file.flagged_category.each do |category| %>
            <li><%=category%>.</li>
            <% end %>
          </ul>
          </strong></p>
        <% end %>
        <p>&nbsp;</p>
        <p>Click "View Content" to continue to the item or "Back to Search" to return to the search results page.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">View Content</button>
        <!-- <button type="button" class="btn btn-danger">Back to Search</button> -->
        <% if request.referer.blank? or URI(request.referer).path != '/catalog' %>
            <%= link_to 'Go Back',  :back, :class => 'btn btn-danger' %>
        <% else %>
            <%= link_back_to_catalog :class => 'btn btn-danger' %>
        <% end %>

      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  // fire the warning modal and make the backdrop very dark
  $('#flagged_warning').modal();
  $(".modal-backdrop").css("opacity",".95");
</script>

app/views/catalog/_show_partials/_show_flagged_notice_download.html.erb
<div class="modal fade" id="flagged_warning" tabindex="-1" role="dialog" aria-labelledby="flaggedWarning">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">EXPLICIT CONTENT WARNING</h3>
      </div>
      <div class="modal-body">
        <p><strong>This item contains content that could be offensive to some viewers or inappropriate for minors.</strong></p>
        <p>&nbsp;</p>
        <p>Click "View Content" to continue to the item or "Back to Search" to return to the search results page.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-warning" data-dismiss="modal">View Content</button>
        <!-- <button type="button" class="btn btn-danger">Back to Search</button> -->
        <% if request.referer.blank? or URI(request.referer).path != '/catalog' %>
            <%= link_to 'Go Back',  :back, :class => 'btn btn-danger' %>
        <% else %>
            <%= link_back_to_catalog :class => 'btn btn-danger' %>
        <% end %>

      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  // fire the warning modal and make the backdrop very dark
  $('#flagged_warning').modal();
  $(".modal-backdrop").css("opacity",".95");
</script>