config/routes.rb
Rails.application.routes.draw do
  # routes for Hist
  mount Hist::Engine => '/hist'

  mount Ckeditor::Engine => '/ckeditor'

  #resources :homosaurus_v2

  #resources :homosaurus_v3

  # Generic file routes
  resources :generic_objects, path: :files, except: :index do
    collection do
      get 'batch_edit'
      post 'batch_add'
      post 'batch_replace'
      post 'batch_delete'
    end
    member do
      get 'stats'
      get 'citation'
      get 'make_public'
      get 'make_private'
      get 'make_redacted'
      get 'regenerate_thumbnail'
      get 'make_coll_image'
    end
  end

  scope module: 'admin', path: '/admin', as: 'admin' do
    get 'carousel_edit', to: 'admin#carousel_edit', as: :carousel_edit
    post 'carousel_update', to: 'admin#carousel_update', as: :carousel_update
  end

  # Collection routes
  resources :collections, path: :col, only: [:show, :index, :new, :edit, :create, :update, :destroy]
  #get 'col', :to => 'collections#public_index', :as => 'collections_public'
  #get 'col/:id', :to => 'collections#public_show', :as => 'collections_public_show'
  get 'col/facet/:id', :to => 'collections#facet', :as => 'collections_facet'
  # Added Institution Routes
  get 'ajax/cols/:id', :to => 'institutions#update_collections', :as => 'generic_files_update_collections'
  get 'ajax/cols', :to => 'institutions#update_collections', :as => 'generic_files_update_collections_no_id'

  get 'places', :to => 'catalog#map', :as => 'places'

  resources :institutions, path: :inst, only: [:show, :index, :new, :edit, :create, :update, :destroy]
  get 'inst/facet/:id', :to => 'institutions#facet', :as => 'institutions_facet'

  # Autocomplete Routes
  get '/autocomplete/creators', to: "autocomplete#creators", as: :creators_autocomplete
  get '/autocomplete/contributors', to: "autocomplete#contributors", as: :contributors_autocomplete
  get '/autocomplete/publishers', to: "autocomplete#publishers", as: :publishers_autocomplete
  get '/autocomplete/language', to: "autocomplete#languages", as: :languages_autocomplete
  get '/autocomplete/dates', to: "autocomplete#dates", as: :dates_autocomplete
  get '/autocomplete/homosaurus_subjects', to: "autocomplete#homosaurus_subject", as: :homosaurus_subject_autocomplete
  get '/autocomplete/homosaurus_v2_subjects', to: "autocomplete#homosaurus_v2_subject", as: :homosaurus_v2_subject_autocomplete
  get '/autocomplete/homosaurus_uri_subjects', to: "autocomplete#homosaurus_uri_subject", as: :homosaurus_uri_subject_autocomplete
  get '/autocomplete/geonames', to: "autocomplete#geonames_subject", as: :geonames_subject_autocomplete
  get '/autocomplete/lcsh_subjects', to: "autocomplete#lcsh_subject", as: :lcsh_subject_autocomplete
  get '/autocomplete/other_subjects', to: "autocomplete#other_subject", as: :other_subjects_autocomplete
  get '/autocomplete/exactMatch', to: "autocomplete#exact_match", as: :exact_match_autocomplete
  get '/autocomplete/closeMatch', to: "autocomplete#close_match", as: :close_match_autocomplete

  get '/autocomplete/exactMatch_lcsh', to: "autocomplete#lcsh_subject", as: :exact_match_lcsh_autocomplete
  get '/autocomplete/closeMatch_lcsh', to: "autocomplete#lcsh_subject", as: :close_match_lcsh_autocomplete
  get '/autocomplete/exactMatch_homosaurus', to: "autocomplete#homosaurus_subject", as: :exact_match_homosaurus_autocomplete
  get '/autocomplete/closeMatch_homosaurus', to: "autocomplete#homosaurus_subject", as: :close_match_homosaurus_autocomplete

  # Added Collection Routes
  get 'collections/members_public/:id' => 'collections#members_public', as: :collection_member_public
  get 'collections/members_private/:id' => 'collections#members_private', as: :collection_member_private
  get 'collections/collection_invisible/:id' => 'collections#collection_invisible', as: :collection_invisible
  get 'collections/collection_visible/:id' => 'collections#collection_visible', as: :collection_visible
  get 'collections/collection_thumbnail_set/:id/:item_id' => 'collections#collection_thumbnail_set', as: :collection_thumbnail_set

  #Static Paths
  resources :abouts, only: [:new, :edit, :create, :update, :show], :path => :about
  resources :learns, only: [:new, :edit, :create, :update, :show], :path => :learn
  resources :page_resources, only: [:new, :edit, :create, :update, :show], :path => :resources
  resources :posts, path: :news

  #get 'feedback' => 'abouts#feedback', as: :feedback
  #post 'feedback' => 'abouts#feedback'
  #get 'feedback_complete' => 'abouts#feedback_complete', as: :feedback_complete
  #get 'subscribe' => 'abouts#subscribe', as: :subscribe
  get 'contact' => 'contact#index', as: :contact
  post 'contact' => 'contact#index'
  #get 'feedback' => 'contact#feedback', as: :feedback
  #post 'feedback' => 'contact#feedback'
  get 'feedback_complete' => 'contact#feedback_complete', as: :feedback_complete

  #get 'about' => 'about#index', as: :about
  get 'about/project' => 'abouts#project', as: :about_project
  #get 'about/news' => 'abouts#news', as: :about_news
  get 'about/team' => 'abouts#team', as: :about_team
  get 'about/board' => 'abouts#board', as: :about_board
  get 'about/policies' => 'abouts#policies', as: :about_policies
  get 'about/contact' => 'abouts#contact', as: :about_contact

  get 'featured' => 'featured#index', as: :featured

  # FIXME: https://github.com/galetahub/ckeditor/issues/919
  get 'icons.png?t=08ffd39', to: redirect('/assets/ckeditor/skins/moono-lisa/icons.png?t=08ffd39')
  get 'icons_hidpi.png', to: redirect('/assets/ckeditor/skins/moono-lisa/icons_hidpi.png')
  get 'icons.png', to: redirect('/assets/ckeditor/skins/moono-lisa/icons.png')



  mount Blacklight::Engine => '/'
  #root to: "catalog#index"
  root to: 'homepage#index'
  devise_for :users
  mount Hydra::RoleManagement::Engine => '/'

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable
  end
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/files', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  


  # advanced routes for advanced search
  get 'search' => 'advanced#index', as: :advanced
  
  resources :downloads, only: 'show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # formats browse
  get 'genre', :to => 'catalog#genre_facet', :as => 'genre_facet'

  # subject browse
  get 'topic', :to => 'catalog#topic_facet', :as => 'topic_facet'

  authenticate :user, -> (user) { user.admin? } do
    mount Blazer::Engine => '/analytics'
  end

  require 'sidekiq/web'
  require 'tilt/erb' # Required for sidekiq-statistic to work
  require 'sidekiq-statistic'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

  resources 'oai',
            only: [:index]
end

app/controllers/catalog_controller.rb
# frozen_string_literal: true
class CatalogController < ApplicationController
  include BlacklightRangeLimit::ControllerOverride
  include BlacklightMaps::ControllerOverride
  include DtaSearchHelper

  include Blacklight::Catalog
  include DtaStaticBuilder

  #layout "sufia-one-column"
  #layout "local_blacklight"

  before_action :get_latest_content
  #before_action :enforce_show_permissions, only: :show
  #skip_before_action :default_html_head

  #CatalogController.search_params_logic += [:add_access_controls_to_solr_params, :add_advanced_parse_q_to_solr, :exclude_unwanted_models]

  before_action  only: [:index, :facet] do
    if current_user.present? and current_user.contributor?
      blacklight_config.add_facet_field 'publisher_ssim', :label => 'Publisher', :limit => 6, :sort => 'index', :collapse => true, :show => true
      blacklight_config.add_facet_field 'visibility_ssi', :label => 'Visibility', :limit => 4, :collapse => false
      blacklight_config.add_facet_field 'dta_homosaurus_v1_subject_ssim', :label => 'Homosaurus V1', :limit => 6, :sort => 'index', :collapse => false

      uploaded_field = 'date_uploaded_dtsi'
      modified_field = 'date_modified_dtsi'
      blacklight_config.add_sort_field "#{uploaded_field} desc", label: "date uploaded \u25BC"
      blacklight_config.add_sort_field "#{uploaded_field} asc", label: "date uploaded \u25B2"
      blacklight_config.add_sort_field "#{modified_field} desc", label: "date modified \u25BC"
      blacklight_config.add_sort_field "#{modified_field} asc", label: "date modified \u25B2"

      blacklight_config.add_sort_field 'collection_name_ssort asc, dta_sortable_date_dtsi asc', :label => "collection \u25B2"
      blacklight_config.add_sort_field 'collection_name_ssort desc, dta_sortable_date_dtsi asc', :label => "collection \u25BC"

      blacklight_config.add_sort_field 'visibility_ssi asc, dta_sortable_date_dtsi asc', :label => "visibility \u25B2"
      blacklight_config.add_sort_field 'visibility_ssi desc, dta_sortable_date_dtsi asc', :label => "visibility \u25BC"

      blacklight_config.add_index_field 'visibility_ssi', :label => 'Visbility'
    else
      blacklight_config.add_facet_field 'publisher_ssim', :label => 'Publisher', :limit => 6, :sort => 'index', :collapse => true, :show => false
    end
  end

  def has_search_parameters?
    params[:dtalimits].present? || super
  end

  configure_blacklight do |config|
    #config.add_facet_field 'publisher_ssim', :label => 'Publisher', :limit => 6, :sort => 'index', :collapse => true, :show => true

    # collection name field
    config.collection_field = 'collection_name_ssim'
    # institution name field
    config.institution_field = 'institution_name_ssim'
    # solr field for flagged/inappropriate content
    config.flagged_field = 'flagged_ssi'

    #config.view.gallery.default = true # List is now the default
    config.view.gallery.partials = [:index_header, :index]
    config.view.masonry.partials = [:index]
    config.view.slideshow.partials = [:index]

    config.show.tile_source_field = :content_metadata_image_iiif_info_ssm
    config.show.partials.insert(1, :openseadragon)

    # Show gallery view
    config.view.gallery.partials = [:index_header, :index]
    config.view.slideshow.partials = [:index]

    # blacklight-maps stuff
    config.view.maps.geojson_field = 'subject_geojson_facet_ssim'
    config.view.maps.coordinates_field = 'subject_coordinates_geospatial'
    config.view.maps.placename_field = 'subject_geographic_ssim'
    config.view.maps.maxzoom = 13
    config.view.maps.show_initial_zoom = 9
    config.view.maps.facet_mode = 'geojson'

    #set default per-page
    config.default_per_page = 15
    config.per_page = [15,25,50,100,200]

    #config.max_per_page = 300
    config.max_per_page = 2000

    ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params
    config.default_solr_params = {
        qt: "search",
        rows: 20
    }

    config.search_builder_class = ::DefaultSearchBuilder

    config.index.title_field = 'title_tesim'
    config.index.display_type_field = 'blacklight_display_ssi'
    config.index.thumbnail_method = :dta_thumbnail_tag

    config.add_facet_field 'dtalimits', label: "Limit", :show => false, query: {
        :ex_fa => { label: 'Exclude Finding Aids', fq: '-genre_ssim:"Finding Aids"' }
    }
    config.add_facet_field 'creator_ssim', label: "Creator", limit: 6, collapse:false
    config.add_facet_field 'dta_all_subject_ssim', :label => 'Topic', :limit => 6, :sort => 'count', :collapse => false
    config.add_facet_field 'dta_other_subject_ssim', :label => 'Subject', :limit => 6, :sort => 'count', :collapse => false
    config.add_facet_field 'dta_dates_yearly_itim', :label => 'Date', :range => { num_segments: 6}, :collapse => false
    config.add_facet_field 'genre_ssim', :label => 'Genre', :limit => 6, :sort => 'count', :collapse => true
    config.add_facet_field 'subject_geographic_ssim', :label => 'Location', :limit => 6, :sort => 'count', :collapse => true
    config.add_facet_field 'language_label_ssim', :label => 'Language', :limit => 6, :sort => 'count', :collapse => true
    config.add_facet_field 'collection_name_ssim', :label => 'Collection', :limit => 8, :sort => 'count', :collapse => true
    config.add_facet_field 'institution_name_ssim', :label => 'Institution', :limit => 8, :sort => 'count', :collapse => true
    config.add_facet_field 'subject_geojson_facet_ssim', :limit => -2, :label => 'Coordinates', :show => false

    config.add_facet_fields_to_solr_request!

    config.add_index_field 'collection_name_ssim', :label => 'Collection'
    config.add_index_field 'institution_name_ssim', :label => 'Institution'
    config.add_index_field "creator_ssim", label: "Creator", itemprop: 'creator'
    config.add_index_field 'date_created_display_ssim', :label => 'Date'
    config.add_index_field 'date_issued_display_ssim', :label => 'Date'

    config.add_search_field('all_fields') do |field|
      field.label = 'All Text'
      field.include_in_advanced_search = false
      field.solr_parameters = { :'spellcheck.dictionary' => 'default' }
    end

    config.add_search_field('title') do |field|
      #field.solr_parameters = { :'spellcheck.dictionary' => 'title' }

      #field.solr_local_parameters = {
          #qf: '$title_qf',
          #pf: '$title_pf'
      #}
      field.solr_parameters = {
          'spellcheck.dictionary': 'title',
          qf: '${title_qf}',
          pf: '${title_pf}'
      }
    end

    config.add_search_field('description') do |field|
      field.solr_parameters = {
          'spellcheck.dictionary': 'description',
          qf: '${description_qf}',
          pf: '${description_pf}'
      }
    end

    config.add_search_field('creator') do |field|
      field.solr_parameters = {
          'spellcheck.dictionary': 'creator',
          qf: '${creator_qf}',
          pf: '${creator_pf}'
      }
    end

    config.add_search_field('publisher') do |field|
      field.solr_parameters = {
          'spellcheck.dictionary': 'publisher',
          qf: '${publisher_qf}',
          pf: '${publisher_pf}'
      }
    end

    config.add_search_field('othersubject') do |field|
      #field.label = 'People / Organizations'
      #field.label = 'People'
      field.label = 'Subject'

      field.solr_parameters = {
          'spellcheck.dictionary': 'othersubject',
          qf: '${othersubject_qf}',
          pf: '${othersubject_pf}'
      }
    end

    config.add_search_field('identifier') do |field|
      field.label = 'Identifier'

      field.solr_parameters = {
          'spellcheck.dictionary': 'identifier',
          qf: '${identifier_qf}',
          pf: '${identifier_pf}'
      }
    end

    # "sort results by" select (pulldown)
    # label in pulldown is followed by the name of the SOLR field to sort by and
    # whether the sort is ascending or descending (it must be asc or desc
    # except in the relevancy case).
    config.add_sort_field 'score desc, title_primary_ssort asc', :label => 'relevance'
    config.add_sort_field 'title_primary_ssort asc, dta_sortable_date_dtsi asc', :label => "title \u25B2"
    config.add_sort_field 'title_primary_ssort desc, dta_sortable_date_dtsi asc', :label => "title \u25BC"
    config.add_sort_field 'dta_sortable_date_dtsi asc, title_primary_ssort asc', :label => "date \u25B2"
    config.add_sort_field 'dta_sortable_date_dtsi desc, title_primary_ssort asc', :label => "date \u25BC"

    # If there are more than this many search results, no spelling ("did you
    # mean") suggestion is offered.
    config.spell_max = 10

    # Configuration for autocomplete suggestor
    config.autocomplete_enabled = true
    config.autocomplete_path = 'suggest'
  end

  # displays values and pagination links for Format field
  def genre_facet
    @nav_li_active = 'explore'
    @facet_no_more_link = true

    @facet = blacklight_config.facet_fields['genre_ssim']
    @response = get_facet_field_response(@facet.key, params)
    @display_facet = @response.aggregations[@facet.key]

    @pagination = facet_paginator(@facet, @display_facet)

    render :full_browse_facet
  end

  def topic_facet
    @nav_li_active = 'explore'
    @facet_no_more_link = true

    @facet = blacklight_config.facet_fields['dta_all_subject_ssim']
    @response = get_facet_field_response(@facet.key, params)
    @display_facet = @response.aggregations[@facet.key]

    @pagination = facet_paginator(@facet, @display_facet)

    render :full_browse_facet
  end
end

app/helpers/catalog_helper.rb
module CatalogHelper
  include Blacklight::CatalogHelperBehavior

# render the date in the catalog#index list view
  def index_date_value options={}
    document = options[:document]
    if document[:date_created_tesim]
      document[:date_created_tesim].first
    elsif document[:date_issued_tesim]
      document[:date_issued_tesim].first
    else
      nil
    end
  end

  def institution_icon_path
    'shared/institution_icon.png'
  end

# determine the 'truncate' length based on catalog#index view type
  def index_title_length
    case params[:view]
      when 'list'
        170
      when 'masonry'
        89
      else
        130
    end
  end


end

app/views/catalog/_bookmark_control.html.erb
<% if current_or_guest_user && !current_or_guest_user.guest %>
  <%-
    # Note these two forms are pretty similar but for different :methods, classes, and labels.
    # but it was simpler to leave them seperate instead of DRYing them, got confusing trying that.
    # the data-doc-id attribute is used by our JS that converts to a checkbox/label.
  -%>

  <% unless bookmarked? document %>
    <%= form_tag( bookmark_path( document ), :method => :put, :class => "bookmark_toggle", "data-doc-id" => document.id, :'data-present' => 'In Favorites', :'data-absent' => 'Favorite', :'data-inprogress' => t('blacklight.search.bookmarks.inprogress')) do %>
      <%= submit_tag(t('blacklight.bookmarks.add.button'), :id => "bookmark_toggle_#{document.id.to_s.parameterize}", :class => "bookmark_add btn btn-default") %>
    <% end %>

  <% else %>

    <%= form_tag( bookmark_path( document ), :method => :delete, :class => "bookmark_toggle", "data-doc-id" => document.id, :'data-present' => 'In Favorites', :'data-absent' => 'Favorite', :'data-inprogress' => t('blacklight.search.bookmarks.inprogress')) do %>
      <%= submit_tag(t('blacklight.bookmarks.remove.button'), :id => "bookmark_toggle_#{document.id.to_s.parameterize}", :class => "bookmark_remove btn btn-default") %>
    <% end %>

  <% end %>
<% else %>
  &nbsp;
<% end %>

app/views/catalog/_constraints.html.erb
<% if query_has_constraints? && (params[:q].present? || params[:f].present?) %>

  <div id="appliedParams" class="clearfix constraints-container">
    <div class="pull-right">
      <%=link_to t('blacklight.search.start_over'), "/catalog?search_field=#{params[:search_field]}", :class => "catalog_startOverLink btn btn-sm btn-text", :id=>"startOverLink" %>
    </div>
    <span class="constraints-label"><%= t('blacklight.search.filters.title') %></span>
    <%= render_constraints(params) %>
  </div>
<% end %>

app/views/catalog/_document_collections_gallery.html.erb
<% # container for all collection documents in collections display view -%>
<div id="documents" class="row collections-gallery">
  <%= render collection: documents,
             as: :document,
             partial: 'index_collections_gallery',
             locals: {count: documents.count} %>
</div>

app/views/catalog/_document_list.html.erb
<%# container for all documents in index view -%>
<div id="search-results">
  <ol class="catalog" start="<%= document_counter_with_offset(0) %>">
    <%#= render documents, as: :document %>
    <% documents.each_with_index do |document, index| %>
        <%= render partial: 'generic_objects/generic_object_list', locals: {document: document, counter: document_counter_with_offset(index)} %>
    <% end %>
  </ol>
</div>

app/views/catalog/_facet_limit.html.erb
<ul class="facet-values list-unstyled">
  <% paginator = facet_paginator(facet_field, display_facet) %>
  <%= render_facet_limit_list paginator, field_name %>

  <% 1==1 || unless paginator.last_page? || params[:action] == "facet" || @facet_no_more_link.present? %>
    <li class="more_facets_link">
      <%= link_to t("more_#{field_name}_html", scope: 'blacklight.search.facets', default: :more_html, field_name: facet_field.label),
                  search_facet_url(id: field_name), class: "more_facets_link" %>
    </li>
  <% end %>
</ul>

<% unless paginator.last_page? || params[:action] == "facet" || @facet_no_more_link.present? %>
  <div class="more_facets_link">
    <%= link_to "More #{facet_field.label} »",
                search_facet_path(id: field_name), class: "more_facets_link" %>
  </div>
<% end %>

app/views/catalog/_facets.html.erb
<% # main container for facets/limits menu -%>
<% skip_title ||= false %>

<% if has_facet_values?  %>
<div id="facets" class="facets sidenav">



  <div class="top-panel-heading panel-heading">
    <div class="collapsed collapse-toggle facets-toggle panel-heading" data-toggle="collapse" data-target="#facet-panel-collapse">
      <span class="sr-only">Toggle facets</span>
      <h3 class="panel-title facet-field-heading">
        <a data-turbolinks="false" data-no-turbolink="true" href="#" class="refine_collapsed"><%= t('blacklight.search.facets.title') %></a>
      </h3>


    </div>

    <% unless skip_title %>
        <h4 class='facets-heading'>
          <%= t('blacklight.search.facets.title') %>
        </h4>
    <% end %>
  </div>
  <div id="facet-panel-collapse" class="collapse panel-group">
    <%= render 'catalog/_show_partials/dta_limits_facet' unless @skip_dta_limits_render  %>
    <%= render 'catalog/_show_partials/dta_admin_facet' if current_or_guest_user.admin? and !@skip_dta_limits_render  %>
    <%= render_facet_partials %>
  </div>

</div>
<% end %>

app/views/catalog/_home_text.html.erb
<div class="page-header row">
  <h2 class="col-md-8 page-heading">Digital Transgender Archive Search</h2>
</div>

<div id="getting-started">
  <h3 class='section-heading'>You have no search specified.</h3>
  <p>Please select a facet on the left or use the search bar above to start a new search. To view all items,
    use the top search bar without any search terms entered.</p>
</div>
<script>
    $(function() {
        //window.location.replace("https://www.digitaltransgenderarchive.net/catalog?utf8=%E2%9C%93&search_field=all_fields&q=");
    });
</script>

app/views/catalog/_index_collections_gallery.html.erb
<%# collection gallery document %>
<div class="masonry document col-xs-6 col-sm-4 col-md-4">
  <div class="thumbnail">
    <%= link_to collection_path(document[:id]) do %><%= render_thumbnail_tag document, { class: "inst_collection_listing_thumbnail" }, { suppress_link: true } %><%end%>
    <div class="caption">
      <h5 class="index_title document-title-heading col-md-12">
      <%= link_to  truncate((document[:title_primary_ssi] || document[:id]),
                                    separator: ' ',
                                    length: index_title_length), collection_path(document[:id]) %>
      </h5>
    </div>
  </div>
</div>

app/views/catalog/_index_gallery_default.html.erb
<% doc_presenter = index_presenter(document) %>
<%# default partial to display solr document fields in catalog index view -%>
<dl class="document-metadata dl-horizontal dl-invert">

  <% index_fields(document).each do |field_name, field| -%>
    <% if should_render_index_field? document, field %>
      <dt class="blacklight-<%= field_name.parameterize %>"><%= render_index_field_label document, field: field_name %></dt>
      <dd class="blacklight-<%= field_name.parameterize %>"><%= doc_presenter.field_value field %></dd>
    <% end -%>
  <% end -%>

</dl>

app/views/catalog/_index_header_generic_file.html.erb
<%# header bar for doc items in index view -%>
<div class="documentHeader row">
  <%# main title container for doc partial view
      How many bootstrap columns need to be reserved
      for bookmarks control depends on size.
  -%>

  <h3 class="index_title document-title-heading col-md-12">
    <% if counter = document_counter_with_offset(document_counter) %>
      <span class="document-counter">
        <%= t('blacklight.search.documents.counter', counter: counter) %>
      </span>
    <% end %>
    <%= link_to_document document, document_show_link_field(document), counter: counter %>
  </h3>
</div>

app/views/catalog/_results_pagination.html.erb
<% if show_pagination? and @response.total_pages > 1 %>
    <div class="row record-padding">
      <div class="col-md-12 pagination-links-container">
        <div id="pagination_links_large" class="pagination">
          <%= paginate @response, :outer_window => 2, :inner_window=>4, :theme => 'blacklight' %>
        </div>
        <div id="pagination_links_medium" class="pagination">
          <%= paginate @response, :outer_window => 1, :inner_window=>3, :theme => 'blacklight' %>
        </div>
        <div id="pagination_links_small" class="pagination">
          <%= paginate @response, :outer_window=>1, :inner_window=>2, :theme => 'blacklight' %>
        </div>
      </div>
    </div>
<% end %>

app/views/catalog/full_browse_facet.html.erb
<div class="facet_container">
<div id="sidebar" class="col-md-3 col-sm-3">
  <div class="side_nav_custom">
    <h4>Browse By</h4>

    <ul class="content">
      <li><%= link_to 'By Map', '/places' %></li>
      <li><%= link_to 'By Institution', institutions_path %></li>
      <li><%= link_to 'By Collection', collections_path %></li>
      <li <% if request.env['PATH_INFO'] == '/topic' %> class="active"<%end%>><%= link_to 'By Topic', topic_facet_path %></li>
      <li <% if request.env['PATH_INFO'] == '/genre' %> class="active"<%end%>><%= link_to 'By Genre', genre_facet_path %></li>
      <li><%= link_to 'By Latest', '/catalog?utf8=%E2%9C%93&sort=date_uploaded_dtsi+desc&search_field=all_fields&q=' %></li>
    </ul>
  </div>
</div>

<div id="content" class="col-xs-12 col-sm-8  col-md-6 col-lg-4">

<div class="modal-header">
  <button type="button" class="ajax-modal-close close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 class="modal-title"><%= facet_field_label(@facet.key) %></h3>
</div>

  <div class="facet_pagination top">
    <%= render :partial=>'facet_pagination' %>
  </div>

<div class="modal-body">
  <div class="facet_extended_list">
    <% if @display_facet.sort == 'index' %>
        <% #Idea from https://groups.google.com/forum/#!searchin/blacklight-development/facet$20case$20insensitive/blacklight-development/TiH6rtTrJcU/pvct08B_ccoJ
           @display_facet.items.sort! { |a,b| a.value.downcase <=> b.value.downcase } %>
    <% end %>

    <% if @display_facet.sort == 'count' %>
        <% #Idea from https://groups.google.com/forum/#!searchin/blacklight-development/facet$20case$20insensitive/blacklight-development/TiH6rtTrJcU/pvct08B_ccoJ
           @display_facet.items.sort_by! { |a| [-a.hits, a.value.downcase] } %>
    <% end %>


       <%= render_facet_limit(@display_facet, layout: false) %>
  </div>
</div>

<div class="modal-footer">

  <div class="facet_pagination bottom">
    <%= render :partial=>'facet_pagination' %>
  </div>
</div>
</div>
</div>