config/routes.rb
Rails.application.routes.draw do
  # routes for Hist
  mount Hist::Engine => '/hist'

  mount Ckeditor::Engine => '/ckeditor'

  #resources :homosaurus_v2

  #resources :homosaurus_v3

  # Generic file routes
  resources :generic_objects, path: :files, except: :index do
    collection do
      get 'batch_edit'
      post 'batch_add'
      post 'batch_replace'
      post 'batch_delete'
    end
    member do
      get 'stats'
      get 'citation'
      get 'make_public'
      get 'make_private'
      get 'make_redacted'
      get 'regenerate_thumbnail'
      get 'make_coll_image'
    end
  end

  scope module: 'admin', path: '/admin', as: 'admin' do
    get 'carousel_edit', to: 'admin#carousel_edit', as: :carousel_edit
    post 'carousel_update', to: 'admin#carousel_update', as: :carousel_update
  end

  # Collection routes
  resources :collections, path: :col, only: [:show, :index, :new, :edit, :create, :update, :destroy]
  #get 'col', :to => 'collections#public_index', :as => 'collections_public'
  #get 'col/:id', :to => 'collections#public_show', :as => 'collections_public_show'
  get 'col/facet/:id', :to => 'collections#facet', :as => 'collections_facet'
  # Added Institution Routes
  get 'ajax/cols/:id', :to => 'institutions#update_collections', :as => 'generic_files_update_collections'
  get 'ajax/cols', :to => 'institutions#update_collections', :as => 'generic_files_update_collections_no_id'

  get 'places', :to => 'catalog#map', :as => 'places'

  resources :institutions, path: :inst, only: [:show, :index, :new, :edit, :create, :update, :destroy]
  get 'inst/facet/:id', :to => 'institutions#facet', :as => 'institutions_facet'

  # Autocomplete Routes
  get '/autocomplete/creators', to: "autocomplete#creators", as: :creators_autocomplete
  get '/autocomplete/contributors', to: "autocomplete#contributors", as: :contributors_autocomplete
  get '/autocomplete/publishers', to: "autocomplete#publishers", as: :publishers_autocomplete
  get '/autocomplete/language', to: "autocomplete#languages", as: :languages_autocomplete
  get '/autocomplete/dates', to: "autocomplete#dates", as: :dates_autocomplete
  get '/autocomplete/homosaurus_subjects', to: "autocomplete#homosaurus_subject", as: :homosaurus_subject_autocomplete
  get '/autocomplete/homosaurus_v2_subjects', to: "autocomplete#homosaurus_v2_subject", as: :homosaurus_v2_subject_autocomplete
  get '/autocomplete/homosaurus_uri_subjects', to: "autocomplete#homosaurus_uri_subject", as: :homosaurus_uri_subject_autocomplete
  get '/autocomplete/geonames', to: "autocomplete#geonames_subject", as: :geonames_subject_autocomplete
  get '/autocomplete/lcsh_subjects', to: "autocomplete#lcsh_subject", as: :lcsh_subject_autocomplete
  get '/autocomplete/other_subjects', to: "autocomplete#other_subject", as: :other_subjects_autocomplete
  get '/autocomplete/exactMatch', to: "autocomplete#exact_match", as: :exact_match_autocomplete
  get '/autocomplete/closeMatch', to: "autocomplete#close_match", as: :close_match_autocomplete

  get '/autocomplete/exactMatch_lcsh', to: "autocomplete#lcsh_subject", as: :exact_match_lcsh_autocomplete
  get '/autocomplete/closeMatch_lcsh', to: "autocomplete#lcsh_subject", as: :close_match_lcsh_autocomplete
  get '/autocomplete/exactMatch_homosaurus', to: "autocomplete#homosaurus_subject", as: :exact_match_homosaurus_autocomplete
  get '/autocomplete/closeMatch_homosaurus', to: "autocomplete#homosaurus_subject", as: :close_match_homosaurus_autocomplete

  # Added Collection Routes
  get 'collections/members_public/:id' => 'collections#members_public', as: :collection_member_public
  get 'collections/members_private/:id' => 'collections#members_private', as: :collection_member_private
  get 'collections/collection_invisible/:id' => 'collections#collection_invisible', as: :collection_invisible
  get 'collections/collection_visible/:id' => 'collections#collection_visible', as: :collection_visible
  get 'collections/collection_thumbnail_set/:id/:item_id' => 'collections#collection_thumbnail_set', as: :collection_thumbnail_set

  #Static Paths
  resources :abouts, only: [:new, :edit, :create, :update, :show], :path => :about
  resources :learns, only: [:new, :edit, :create, :update, :show], :path => :learn
  resources :page_resources, only: [:new, :edit, :create, :update, :show], :path => :resources
  resources :posts, path: :news

  #get 'feedback' => 'abouts#feedback', as: :feedback
  #post 'feedback' => 'abouts#feedback'
  #get 'feedback_complete' => 'abouts#feedback_complete', as: :feedback_complete
  #get 'subscribe' => 'abouts#subscribe', as: :subscribe
  get 'contact' => 'contact#index', as: :contact
  post 'contact' => 'contact#index'
  #get 'feedback' => 'contact#feedback', as: :feedback
  #post 'feedback' => 'contact#feedback'
  get 'feedback_complete' => 'contact#feedback_complete', as: :feedback_complete

  #get 'about' => 'about#index', as: :about
  get 'about/project' => 'abouts#project', as: :about_project
  #get 'about/news' => 'abouts#news', as: :about_news
  get 'about/team' => 'abouts#team', as: :about_team
  get 'about/board' => 'abouts#board', as: :about_board
  get 'about/policies' => 'abouts#policies', as: :about_policies
  get 'about/contact' => 'abouts#contact', as: :about_contact

  get 'featured' => 'featured#index', as: :featured

  # FIXME: https://github.com/galetahub/ckeditor/issues/919
  get 'icons.png?t=08ffd39', to: redirect('/assets/ckeditor/skins/moono-lisa/icons.png?t=08ffd39')
  get 'icons_hidpi.png', to: redirect('/assets/ckeditor/skins/moono-lisa/icons_hidpi.png')
  get 'icons.png', to: redirect('/assets/ckeditor/skins/moono-lisa/icons.png')



  mount Blacklight::Engine => '/'
  #root to: "catalog#index"
  root to: 'homepage#index'
  devise_for :users
  mount Hydra::RoleManagement::Engine => '/'

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable
  end
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/files', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  


  # advanced routes for advanced search
  get 'search' => 'advanced#index', as: :advanced
  
  resources :downloads, only: 'show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # formats browse
  get 'genre', :to => 'catalog#genre_facet', :as => 'genre_facet'

  # subject browse
  get 'topic', :to => 'catalog#topic_facet', :as => 'topic_facet'

  authenticate :user, -> (user) { user.admin? } do
    mount Blazer::Engine => '/analytics'
  end

  require 'sidekiq/web'
  require 'tilt/erb' # Required for sidekiq-statistic to work
  require 'sidekiq-statistic'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

  resources 'oai',
            only: [:index]
end

app/models/page_resources.rb
class PageResources < ActiveRecord::Base
  self.primary_key = 'url_label'
end

app/controllers/page_resources_controller.rb
class PageResourcesController < ApplicationController
  include DtaStaticBuilder

  before_action :get_latest_content

  before_action :set_nav_heading

  before_action :verify_superuser, only: [:new, :create, :edit, :update]

  #layout 'static_layout'

  def edit
    @page = PageResources.find(params[:id])
    gon.compiled_application_css = Rails.application.assets["application.css"].to_s
  end

  def update
    @page = PageResources.find(params[:id])
    #@page.destroy!
    #@page = Learns.new(page_params)
    @page.update(page_params)

    if @page.save
      redirect_to page_resource_path(:id => @page), notice: "Page was updated!"
    else
      redirect_to page_resources_path, notice: "Could not update page"
    end
  end

  def new
    @page = PageResources.new
    gon.compiled_application_css = Rails.application.assets["application.css"].to_s
  end

  def create
    @page = PageResources.new(page_params)

    if @page.save
      redirect_to page_resource_path(:id => @page.id)
    else
      #redirect_to post_path(:id => @post.id)
      redirect_to new_page_resource_path, notice: "Could not create about page"
    end
  end

  def show
=begin
    if params[:id] == "guide"
      render "learns/guide"
    elsif params[:id] == "raceandethnicity"
        render "learns/raceandethnicity"
    else
      @page = Learns.find(params[:id])
    end
=end

    @page = PageResources.find(params[:id])

  end

  def set_nav_heading
    @nav_section = 'Resources'
    @nav_items = []

    if current_user.present? and current_user.superuser?
      nav_items_raw = PageResources.all.order("link_order")
    else
      nav_items_raw = PageResources.where(:published=>true).order("link_order")
    end

    nav_items_raw.each do |nav_item|

      if params[:id].present? and params[:id] == nav_item.url_label
        #@nav_items << nav_item.title
        @nav_items << (ActionController::Base.helpers.link_to nav_item.title, page_resource_path(:id=>nav_item), {class: 'active'})
      else
        @nav_items << (ActionController::Base.helpers.link_to nav_item.title, page_resource_path(:id=>nav_item))
      end

    end

  end

  def page_params
    params.require(:page).permit(:url_label, :title, :published, :content, :link_order)
  end


end

app/views/page_resources/edit.html.erb
<div id="static_holder" class="container-fluid">
  <div class="row">
    <%= render partial: '/partials/section_side_nav' %>
    <div class="col-xs-9 col-sm-9 static_holder_content_container">
      <div id="static_holder_content" class="static_holder_content">
        <h2>Update Resource</h2>


        <%= simple_form_for(@page, :url => page_resource_path(:id => @page), :as => :page, multipart: true) do |f| %>

            <%= f.input :title, :required=>true, :input_html => {:value=>@page.title}  %>

            <%= f.input :url_label, :as => :string, :label=>'URL Label (like "project")', :required=>true, :input_html => {:value=>@page.url_label}  %>

            <% my_toolbar = [
                { name: 'document', items: [ 'Maximize', 'ShowBlocks','-', 'Source','-','About'] },
                { name: 'clipboard', items: [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo', '-', 'Find', 'Replace', '-',  'SpellChecker', 'Scayt'] },
                '/',
                { name: 'styles', items: [ 'Styles', 'Format', 'FontSize' ] },
                { name: 'links', items: [ 'Link','Unlink','Anchor' ] },
                { name: 'insert', items: [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak','Iframe' ] },
                '/',
                { name: 'basicstyles', items: [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ] },
                { name: 'colors', items: [ 'TextColor', 'BGColor' ] },
                { name: 'paragraph', items: [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv',
                                              '-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ] },


            ]; %>

            <%= f.input :content, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => my_toolbar, :height=>'500'}, :value=>@page.content}, :required=>true  %>
            <script>
              $( document ).ready(function() {
                //CKEDITOR.replace('content', {height: 1000});
              });
            </script>

            <%= f.input :link_order, :as=>:integer,:input_html => { :style=>"width:75px;", :value=>@page.link_order }, :required=>true   %>

            <%= f.input :published, as: :boolean, :label=>'Visible?', :input_html => {:value=>@page.published}  %>

            <%= f.button :submit %>

        <% end %>
      </div>

    </div>

  </div>
</div>

app/views/page_resources/new.html.erb
<div id="static_holder" class="container-fluid">
  <div class="row">
    <%= render partial: '/partials/section_side_nav' %>
    <div class="col-xs-9 col-sm-9 static_holder_content_container">
      <div id="static_holder_content" class="static_holder_content">
        <h2>Add Resources Page</h2>

        <%= simple_form_for(@page, :url => page_resources_path, :as => :page, multipart: true) do |f| %>

            <%= f.input :title, :required=>true  %>

            <%= f.input :url_label, :as => :string, :label=>'URL Label (like "project")', :required=>true  %>

            <% my_toolbar = [
                   { name: 'document', items: [ 'Maximize', 'ShowBlocks','-', 'Source','-','About'] },
                   { name: 'clipboard', items: [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo', '-', 'Find', 'Replace', '-',  'SpellChecker', 'Scayt'] },
                   '/',
                   { name: 'styles', items: [ 'Styles', 'Format', 'FontSize' ] },
                   { name: 'links', items: [ 'Link','Unlink','Anchor' ] },
                   { name: 'insert', items: [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak','Iframe' ] },
                '/',
                   { name: 'basicstyles', items: [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ] },
                   { name: 'colors', items: [ 'TextColor', 'BGColor' ] },
                   { name: 'paragraph', items: [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv',
                                                 '-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock','-','BidiLtr','BidiRtl' ] },


               ]; %>

          <%= f.input :content, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => my_toolbar, :height=>'500'}}, :required=>true  %>
            <script>
              $( document ).ready(function() {
              //CKEDITOR.replace('content', {height: 1000});
              });
            </script>

            <%= f.input :link_order, :as=>:integer,:input_html => { :style=>"width:75px;" }, :required=>true   %>

            <%= f.input :published, as: :boolean, :label=>'Visible?'  %>

            <%= f.button :submit %>

        <% end %>
      </div>

    </div>

  </div>
</div>

app/views/page_resources/show.html.erb
<% @page_title = "#{@page.title} -  #{application_name}" %>
<div id="static_holder" class="container-fluid">
  <div class="row">
    <%= render partial: '/partials/section_side_nav' %>
    <div class="col-xs-12 col-sm-9 col-lg-9 col-md-9 static_holder_content_container">
      <div id="static_holder_content" class="static_holder_content">
        <a name="top"></a>
        <h2><%=@page.title %><% if current_user.present? and (current_user.superuser? or (current_user.admin? and !@page.published))%><span style="color:red;"> <%= link_to "[Edit]", edit_page_resource_path(@page) %></span><%end%></h2>

        <%=@page.content.html_safe%>

        <%= render partial: "partials/back_to_top" %>

      </div>

    </div>

  </div>
</div>